### ISSUE TITLE
Function to start external program

### ISSUE THREAD

**Issue by MuhKuh7** [BananaAccounting/General#2]
It would be cool to have a possibility to call an external program from within an app.

I am using a DMS for all my documents and store the ID in Banana. Now I would like to create an app that allows me to open the linked document in my DMS client. To do that I need the possibility to call an external program with an argument.

**Comment by dzucchetti** [comment]
For security reason, for the moment BananaApps cannot directly write to 
file or call external programs.

On 26.10.2015 19:37, MuhKuh7 wrote:

> It would be cool to have a possibility to call an external program 
> from within an app.
> 
> I am using a DMS for all my documents and store the ID in Banana. Now 
> I would like to create an app that allows me to open the linked 
> document in my DMS client. To do that I need the possibility to call 
> an external program with an argument.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/BananaAccounting/General/issues/2.

## 

Domenico Zucchetti
lic. iur HSG
Managing Director
Banana.ch SA
via Trevano 7a
CH-6900 Lugano
Tel. +4191 921 30 29
Fax +4191 921 30 48
Internet: http://www.banana.ch

## e-mail: domenico@banana.ch

**Comment by dzucchetti** [comment]
Do you have any suggestion on how we could provide a way to call your software without compromizing the security model?

**Comment by MuhKuh7** [comment]
One option would be to explicitly let the user enable such a feature in the settings. Similar to the filetypes you can configure as secure.

Another idea is to allow the execution of an URI with a specific scheme. A function like "openUri" or similar. I could then use the DMS URI provided by the DMS system. dms://localhost/doc/20. The real URI is much more complex, but you get the idea ;)

I know that there are already columns in the tables that allow URLs, but I have 2 problems with them. First they seem to allow http/https only, and second from a user perspective it is much easier to enter the document ID instead of an URL.

**Comment by MuhKuh7** [comment]
Do you have any news regarding this? I really would like to connect Banana to my DMS.

**Comment by dzucchetti** [comment]
I will like to speak with you to see what could be the best technology to solve the problem. 
Could you call us o send an email with your coordinate. 
Domenico
