### ISSUE TITLE
Template to import Transactions

### ISSUE THREAD

**Issue by samzuercher** [BananaAccounting/General#20]
I'm sorry, but i was not able to find anywhere a template describing how the data should be structured to be imported into banana. I don't want to write a seperate plugin or extension, i would get the data from the bank and transfer it into a file01.txt and import it into banana. I would also like to set the Debit- and Credit-Account-Numbers, something like this:

"Date","Doc","Description","AccountDebit","AccountCredit","Amount"
2022-10-12,1,Desc 01, 1020, 2820, 2000
2022-10-19,1,Desc 02, 6570, 1020, 300

As far as i understand my options are:
- 'ISO 20022'
- 'MT940'
- 01.txt with unknown structure ("Bewegungen Einnahmen-Ausgaben")
- 02.txt with unknown structure ("Datei mit Text mit Überschrift Spalten")

I'm not sure if it is possible to set the Debit- and Credit-Accounts in ISO 20022 and MT940. Therefore i thought to try the .txt-files, but it still did not work.

The above sample is imported like this:
<html><body>

12/10/2022 | 1 | Desc 01 | [A] | [CA]
-- | -- | -- | -- | --
19/10/2022 | 1 | Desc 02 | [A] | [CA]

</body></html>

Is there any solution?

**Comment by PloszajAaron** [comment]
Good morning, 

thank you for your feedback,

If your intention is to modify the fields to set the accounts in the debit and credit columns, you have chosen the correct procedure. In fact, Banana allows you to import transactions from any *.txt/*.csv file as long as it respects the format indicated in [our documentation](https://www.banana.ch/doc/en/node/9966). 

The format of the example you have sent us is also correct, as far as the import procedure is concerned, I advise you to try the one described in our documentation: [Import Double-entry transactions in CSV format](https://www.banana.ch/doc/en/node/9947), in this way, it should work correctly. For other import procedures, the column fields are predefined and cannot be changed.

Just in case you want to be sure that you are using the correct format, you can try to export the rows from the transactions table and check if the format of the exported data is the same of the data you would like to import. To export the rows you can go on Data->Export rows->Export rows to txt.

Let me know if you have any other problems.

Aaron Ploszaj
Banana.ch SA

**Comment by samzuercher** [comment]
What i end up doing is exporting the transactions as text-file and then use the same structure for import. It depends on how many columns are visible in banana.
