### ISSUE TITLE
QML example

### ISSUE THREAD

**Issue by MuhKuh7** [BananaAccounting/General#3]
Could you add a simple QML example that demonstrates how to use QtQuick in Banana?

It seems that even the most simple hello world scripts I create only result in an empty window with a waiting cursor, while they work perfectly in Qt Creator.

**Comment by dzucchetti** [comment]
Sorry, for the moment we do not allow to execute QML scripts, for the fact that they can do evil.

**Comment by MuhKuh7** [comment]
Ok, this fact seems to be missing from the documentation of "createQml" ;)

https://www.banana.ch/cms/de/node/4725
http://doc8.banana.ch/en/node/4725

**Comment by dzucchetti** [comment]
Thanks we have removed the information, in doc8.
We will later on completely remove the documentation on www.banana.ch
