### ISSUE TITLE
Import filter

### ISSUE THREAD

**Issue by fuerst** [BananaAccounting/General#4]
I'm looking for an examples of an import filter script for importing transactions (CSV) into accounting. In _General/TutorialApps/tutorial2.ac2_ there is an section _IMPORT_ within the _Documents_ tab. It is empty though. I tried to adopt the existing _ch.banana.filter.import.raiffeisen.js_ to the format used by my Bank (GLS Bank, Germany) but ended up with the _Unknow format_ error. 

Question is: how do I debug an import filter script?

**Comment by dzucchetti** [comment]
Thank for your feedback.
We have added a new page especially for importing CSV https://github.com/BananaAccounting/General/tree/master/ImportApps with a better template and more information
Le us know.

**Comment by fuerst** [comment]
That works great, thanks! I now have a working import filter for the CSV transaction export file of GLS Bank (Germany). 

Two notes though:
1. I have to `Banana.Converter.toInternalAmountFormat(convertedData["Income"]);` inside `postProcessIntermediaryData()` to actually get the amount imported.
2. After selecting a CSV file from the _Import into accounting_ dialog and clicking _OK_ I get a _File not found_ error (systemmsg::err_filenontrovato). Importing CSV data from the clipboard works well though.

**Comment by dzucchetti** [comment]
Perfect!
Do you want to contribute back? In case do it on the same directory. 
1. I think the `Banana.Converter.toInternalAmountFormat(convertedData["Income"]);` could be used also in the defineConversionParam.
2. It is a know bug in Banana with relative path, that will be fixed in a next release.
3. We have also developped other tools for Germany that are not yet published. In case you have some more needs contact me at domenico@banana.ch

**Comment by fuerst** [comment]
Would be glad to share. What about naming of the file. Should it something like _import.glsbank.template.js_, _ch.banana.filter.import.glsbank.js_ or _de.fuerstnet.import.filter.glsbank.js_ (my company).

**Comment by dzucchetti** [comment]
Thank. We have not yet set standards.
But I think. "import.de.glsbank.csv.js" would be ok. It would be interesting also to have one csv file (just one row of data) "import.de.glsbank.csv.csv".
